class_name QuestConstants

const PRESSURE_INCREASE_PER_CORRECT_ANSWER = 1000
const PRESSURE_DECREASE_PER_WRONG_ANSWER = 1500
const MAX_PRESSURE = 10000
const MAX_ADDED_PROGRESS = 1000
const REQUIRED_PROGRESS = 1000
